### ISSUE TITLE
Handle Svelte events

### ISSUE THREAD

**Issue by subpx** [tjinauyeung/svelte-forms-lib#1]
I have come to an issue when trying to validate custom components. I have a case where I need to be able to handle svelte events. This is because they are not fired from a HTML element and the attached value is not the same as the value of an element (example being an autocomplete where the input does not always have the same value as the value needed to be sent with the event)

It would be great to be able to pass a Svelte event to the handleChange method. This would give more flexibility when handling these events.

Probably something like dispatch('eventName', {name,value});

I am happy to contribute, just wondering what your thoughts are?

Thanks for good work on the lib.

**Comment by tjinauyeung** [comment]
Hi subx, thanks for submitting an issue.

Can you give a code example of how you want to use it?

**Comment by subpx** [comment]
https://github.com/subpx/svelte-forms-lib-examples/commit/55abfae414ad5f4356714529a500ca232883f2c4

**Comment by tjinauyeung** [comment]
Thanks for the example; in this case I'll need to read up on Svelte events a bit before I can think of a solution.

However, please feel free to experiment and create a PR! I happily review it.

**Comment by tjinauyeung** [comment]
```

**Comment by kbytesys** [comment]
Yep, it could be usefull.

I'm wrapping the custom event at the moment:

```
export function wrapCustomChangeEvent(event) {
    return {
        target: {
            name: event.detail.name,
            value: event.detail.value
        }
    }
}
```
and I'm using this function this way in the svelte component:
```
on:change={(event) => handleChange(wrapCustomChangeEvent(event))}
```

I think it's better to use a different function name maybe: handleCustomEvent?

**Comment by subpx** [comment]
@tjinauyeung yes that is perfect.

**Comment by tiaanduplessis** [comment]
I'm closing this issue as `updateValidateField` added by @kbytesys provides this ability to work with custom events.
