### ISSUE TITLE
did not export their `package.json` file so we could not check the "svelte" field

### ISSUE THREAD

**Issue by evdama** [tjinauyeung/svelte-forms-lib#112]
Upgrading from 1.9.0 to 1.10.0 I'm getting this error in my Sapper app:

```
[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

- svelte-forms-lib
```

**Comment by larrybotha** [comment]
@evdama thanks for reporting - it seems that one does not simply add `exports` to `package.json`.

I've reverted with #113 and tested the update locally and everything looks good again - please reopen if you experience issues.

**Comment by evdama** [comment]
I upgraded to 1.10.1 and indeed, the error is gone. Thanks much 👍
