### ISSUE TITLE
Should submitting a form update initial values

### ISSUE THREAD

**Issue by subpx** [tjinauyeung/svelte-forms-lib#124]
I thinking of making an update and wanted to get someones thoughts before I do it.

What I wanted to do was update initial values once a form is submitted.

At the moment what happens is the initial values do not get updated once a form is successfully submitted, so when a user then resets the form, the form values are set to the original values.

Thoughts?

**Comment by larrybotha** [comment]
Hmm, so something like calling `updateInitialValues` over here: https://github.com/tjinauyeung/svelte-forms-lib/blob/master/lib/create-form.js#L122 ?

It seems like a good idea, and I don't see why we couldn't implement it. What I don't understand is why the values aren't persisted after a user submits - can you provide a repro?

Other things to consider:
- would this require a minor or major version bump? Some users may be relying on the existing behaviour, so a major version bump seems sensible
- we'd need tests to validate the post-submission values

**Comment by subpx** [comment]
@larrybotha thanks for the comment. We can close this issue I think.
Done some more thinking and research and I was barking up the wrong tree.

Having said that:

1. handleReset is not even in the docs. I'll get around to adding that soon. 
2. From research it is recommended to not have a reset button on a form these days anyway, so I am not too fussed about this.
3.  If we were to update anything, handleReset should really clear all values in the form, not reset back to the initial values. This is the native behaviour of a HTML form.

**Comment by larrybotha** [comment]
Excellent, thanks for the feedback @subpx. I'll close this out, but feel free to open if you want to revisit it

**Comment by jtlapp** [comment]
I do need a way to reset to initial values, but it's not on user request. I need the form to start clean on each load. Right now my prior input values are superseding the initial values in my modal.

`handleReset` only works when binding inputs to the `$form` values, which `Field` does not do. So I guess I need to manually write the code for resetting the form to initial values?
