### ISSUE TITLE
TextArea, CheckBox

### ISSUE THREAD

**Issue by ohmaye** [tjinauyeung/svelte-forms-lib#13]
**Is your feature request related to a problem? Please describe.** 
Feature request: Expose "key" in key.js.

Thanks! I've used Formik in the past and your implementation is very easy to understand. 
I needed to use textarea and checkboxes (modifying value to true/false), but the slots in Form don't give me access to the "key" to the store. So, I couldn't add custom components.

**Describe the solution you'd like**
Allowing let:key would open up to custom components. Of course, could add the most common ones to the library, but just exposing the key in key.js would suffice -- I think.

**Describe alternatives you've considered**
I copied the library into my source to make these customizations, which is not optimal.

**Comment by tjinauyeung** [comment]
Great suggestion

**Comment by tjinauyeung** [comment]
The only thing I realise now is that the regular helper components i.e. `Field` and `Select` will have the custom key passed in as well in order to connect to the correct `Form` instance. So the template will become

```
<script>
import { Form } from 'svelte-forms-lib';
import RedInput from './RedInput';

const key = "my-form";

const form = createForm({
  initialValues: {
    name: ''
  },
  validationSchema: yup.object.shape({
    name: yup.string
  }),
  onSubmit: values => console.log(values)
});
</script>

<Form let:key={key} {...form}>
  <RedInput name="name" />
  <Field let:key={key}>
</Form>
```

Which is not ideal. Any thoughts on how to avoid this boilerplate?

**Comment by ohmaye** [comment]
Thanks for the follow up. 

Wouldn't it be simpler if you just export/expose the key (in key.js) instead of allowing custom keys? 

I don't see much benefit in being able to create custom keys.

**Comment by larrybotha** [comment]
`key` is now exported as per https://github.com/tjinauyeung/svelte-forms-lib/pull/89
