### ISSUE TITLE
handleChange definition in FormState type definition is incorrect

### ISSUE THREAD

**Issue by letoast** [tjinauyeung/svelte-forms-lib#140]
inside /lib/index.d.ts:
```
type FormState<Inf = Record<string, any>> = {
  ...
  handleChange: () => void; <-------
  ...
};
```
which is incorrect, since the function's definition inside create-form.js is
```
 function handleChange(event) {
    const element = event.target;
    const field = element.name || element.id;
    const value = isCheckbox(element) ? element.checked : element.value;

    return updateValidateField(field, value);
  }
```
this produces an annoying warning if you try to pass an event to the function manually....

**Comment by larrybotha** [comment]
@letoast thanks for raising the issue. Please check out v1.10.9 and let me know if you have any issues

**Comment by letoast** [comment]
Haven't checked the update yet, but just by looking at the type definition, it still doesn't match the function definition.
As far as I know typescript, the type definition should be:

handleChange(event: Event) => any

That way, typescript shouldn't report that the function is expecting 0 arguments if you pass in event when calling it.

**Comment by larrybotha** [comment]
derp, you're right... I was being lazy and didn't evaluate the actual function thoroughly. Thanks @letoast - added the missing parameter to the function signature in #145

**Comment by letoast** [comment]
No probs, thank you for the fast update!
