### ISSUE TITLE
Can't disable the submit button when using the helper components

### ISSUE THREAD

**Issue by kevinrenskers** [tjinauyeung/svelte-forms-lib#16]
`createForm` exposes observables like `isValid`, which can be used to disable the submit button for example. See https://svelte-forms-lib-sapper-docs.now.sh/observables.

When using the [helper components](https://svelte-forms-lib-sapper-docs.now.sh/helpers), you don't have access to these observables, so you can't disable the submit button, or do other things related to observables.

Any way this can be improved?

**Comment by tjinauyeung** [comment]
I'm looking into exposing a `key` which is used internally to share the Form state with its children.

This technique will also allow for all other properties such as isValid, isTouched, etc to be accessed and changed.

The API could look something like:

```
<script>
  import { Form } from 'svelte-forms-lib';
  import { getContext } from 'svelte/context';
 
  const key = "my-custom-key";
  const { isValid, isTouched } = getContext(key);
</script>

<Form let:key={key} {...props}>
  <Field name="name"/>
  <button disabled={!isValid$} type="submit">submit</button>
</Form>
```

What do you think?

**Comment by kevinrenskers** [comment]
Well, I ended up not using this library anymore. I figured that literally all I needed was this simple function:

``` javascript
export function copy(value) {
  return JSON.parse(JSON.stringify(value));
}

export function createForm(config) {
  let values = copy(config.initialValues || {});
  let required = config.required || [];

  const form = writable(values);
  const isSubmitting = writable(false);

  const isValid = derived(form, $form => {
    return formIsValid($form);
  });

  function formIsValid(values) {
    let valid = true;

    required.forEach(field => {
      if (!values[field]) {
        valid = false;
      }
    });

    return valid;
  }

  function handleSubmit(ev) {
    if (ev && ev.preventDefault) {
      ev.preventDefault();
    }

    if (!formIsValid(values)) {
      // Invalid form
      return;
    }

    return Promise.resolve()
      .then(() => isSubmitting.set(true))
      .then(() => config.onSubmit(values))
      .finally(() => isSubmitting.set(false));
  }

  return {
    form,
    isValid,
    isSubmitting,
    handleSubmit,
  }
}
```

That's enough for me to build any form I want, with loading indication, checking for required fields, disabling submit buttons, etc. Of course it does way less than your library, but it's so simple that I don't even need helper components :)

```
<script>
  import { saveDocument } from "../firebase";
  import { createForm } from "../utils";
  import { LoadingOverlay } from "../components";

  export let location;

  const { form, isValid, isSubmitting, handleSubmit } = createForm({
    initialValues: location.fields,
    required: ["name"],
    onSubmit: values => {
      return saveDocument(location.ref, values).then(result => {
        // Do stuff on success
      });
    },
  });
</script>

<form class="form" on:submit={handleSubmit}>
  <div class="row">
    <label for="name">Name</label>
    <input name="name" type="text" bind:value={$form.name} />
  </div>

   <div class="row">
    <button type="submit" disabled={!$isValid || $isSubmitting}>Save</button>
  </div>
</form>

{#if $isSubmitting}
  <LoadingOverlay />
{/if}
```

Select, textarea, checkboxes, radiobuttons, everything just works without the need for any helper components, and since there is no need for an `on:change` on every field, there really is no need for helper components because there is no boilerplate to reduce.

**Comment by tjinauyeung** [comment]
Looks great! Thanks for sharing.

I'll close this issue then.

**Comment by DanChristos** [comment]
This issue was closed, but still the original suggestion would be a nice feature. Currently, it doesn't seem to be possible to access the observables while using the helper components. Or has this been addressed now that it's 2 years later?
