### ISSUE TITLE
formProps dynamic initialValues are no changing

### ISSUE THREAD

**Issue by JulianRojasBet** [tjinauyeung/svelte-forms-lib#18]
Hello! I am not sure if this is a bug but is something that is working wrong for me.

I am making a CRUD for a entity called Material where on update, a Modal-Form should show the data of "related material". For that I create a store for the `currentMaterial` which is the "related material", and a derived store for the `formProps` that use `currentMaterial` as `initialValues` and that working fine. The problem occur on the `<Form {...$formProps}>` statement that appears that Form's initialValues are not changing even when the `$formProps` have changed.

**Screenshots**
Here is an example of what the form `values` are and what the `$formProps` `initialValues` actually are.
![image](https://user-images.githubusercontent.com/35241159/81020561-b3899700-8e2e-11ea-8733-c657b4423d8b.png)

Here is my code:
![store](https://user-images.githubusercontent.com/35241159/81021818-a8843600-8e31-11ea-88c1-9e0d2edbacd7.png)
![material](https://user-images.githubusercontent.com/35241159/81021824-ab7f2680-8e31-11ea-9f3b-fba9c512f1bf.png)

**Comment by axtn** [comment]
Did you ever figure this out?

**Comment by axtn** [comment]
I just decided to try to fix this myself. My solution works nicely for my implementation locally, setup a PR:

https://github.com/tjinauyeung/svelte-forms-lib/pull/24

**Comment by larrybotha** [comment]
fixed by https://github.com/tjinauyeung/svelte-forms-lib/pull/24
