### ISSUE TITLE
ValidateField function

### ISSUE THREAD

**Issue by kbytesys** [tjinauyeung/svelte-forms-lib#21]
We often use the binding of the form data in the input/child component:

```
    <input
      id="name"
      name="name"
      on:change={handleChange}
      on:blur={handleChange}
      bind:value={$form.name}
    />
```
The handle change play two roles: 
1) it validate the value received from the html event 
2) assign the value to the field if the value is valid

*BUT*: the value is already changed by the svelte binding and sometime you can't use the value from the html event because it isn't the object value, but just a string.

With a validateField function, we can solve both issues and we can trigger the field validation also when we change the value programmatically. Examples:

```
<script>
$form.name = "blabla"
validateField("name")
<script>

    <input
      id="name"
      name="name"
      on:change={() => validateField("name")}
      on:blur={() => validateField("name")}
      bind:value={$form.name}
    />
```

It could be usefull also a function that sets and validates a field
```
changeValue("name", value);
```

**Comment by subpx** [comment]
@kbytesys this is great! I've tried it out and it solves my issue #1 
Much better than using Svelte custom events. THANKS

@tjinauyeung You should add this to the docs and merge this PR

**Comment by eugbyte** [comment]
I know the issue is solved, but it would be good if this function is documentation (https://svelte-forms-lib-sapper-docs.vercel.app/custom).

This function is useful for programmatically trigger validation.
