### ISSUE TITLE
clearErrorsAndSubmit ignores validation schema

### ISSUE THREAD

**Issue by subpx** [tjinauyeung/svelte-forms-lib#26]
When clearErrorsAndSubmit is run it uses util.assignDeep(values, "") to "clear" the error state for the current values. 

The problem I have found is with nested objects. You may have properties on an object that you dont want validated. OR in my case 

`
country: yup
        .object().shape({})
        .required()
        .nullable()
`

Where I do not want any properties of the country object validated. Once the form is submitted and the errors cleared, every property and all nested objects will be added to the error state object.

**To Reproduce**
Steps to reproduce the behaviour:
1. As above. Validate for an object, ignoring any of its properties. error would be 
`country: ""`
2. Pass validation and attempt to submit form. Once the form is cleared the error state is now something like
`country: { name:"", coords: {lat:"", lng""}}`

**Expected behavior**
The error state should be "cleared" using the validation schema. OR could it just be set to an empty object?

**Comment by tjinauyeung** [comment]
Great find. I've looked into the PR and added a small comment.

**Comment by subpx** [comment]
Just checking to see if this project is still alive?
If so I am going to get back onto this. I have a good idea on how to solve this issue.

**Comment by larrybotha** [comment]
@subpx yup, still alive! Thanks for your contributions so far.
