### ISSUE TITLE
<select>'s initial default value is not synced with form store

### ISSUE THREAD

**Issue by damooo** [tjinauyeung/svelte-forms-lib#4]
Hi @tjinauyeung, thanks for lib.. it's pretty nice architecture
when we populate `<select>` elem with `<option>` elems on dynamically retrieved data, then browser treats first option as default selected value. but it seems form store doesn't get updates to that default value, but sits with initial filler value. only when we change to other value, it changes.

**Comment by tjinauyeung** [comment]
Will look into it @damooo! Thanks for the issue.

**Comment by tjinauyeung** [comment]
For now a solution would be to initialize the default value in the `initialValues` object

```js
const DEFAULT_OPTION = 'Mr.';

const {...handlers, etc} = createForm({
  initialValues: {
    title: DEFAULT_OPTION // initialise your select component with the default option
  },
  // other props
});
```

**Comment by tjinauyeung** [comment]
Does this make sense @damooo?

**Comment by damooo** [comment]
@tjinauyeung Thanks.
But, when we are initializing the form, there is no data. all options are dynamic, will be known only at run time. So default option is not known.

**Comment by tjinauyeung** [comment]
I see what you mean now. 

Currently, the select will only update when the `handleChange` is called or the form state is changed. The latter is done as follows:

`createForm` returns a `form` variable. This is an observable representing the form values. You can manipulate this change the form state when the options are fetched:

```js
const { form } = createForm({
  initialValues: {
    title: ""
  },
  onSubmit: (values) => alert(values)
});

getDynamicTitles().then(titles => {
  $form.title = titles[0] // set the title
});
```

Let me know if this works!

**Comment by damooo** [comment]
@tjinauyeung 
That still has a problem that, it triggers svelte reactivity over $form, without user's explicit action. In some cases it is unwanted.

**Comment by tjinauyeung** [comment]
And what about initialising the form áfter the dynamic data has been fetched? Is that an option?

I'm open to other suggestions btw, just need to have a bit of a think on this.

**Comment by damooo** [comment]
In such cases, `form` binding is not a store, until it is initialized, and we cannot refer to it using $form anywhere, even after it is initialized. as svelte checks at compile time and raises error.

One solution i can think of is to make `createForm` accept an optional parameter `formStore:Writable`. If it is passed, it will be used and returned as `form`, otherwise new one. This way, even before initialization,  store does exists, with what ever value, and we can refer to it in svelte component with '$form` syntax,

**Comment by damooo** [comment]
hello @tjinauyeung ,
Are you able to get to a way for it? It is very normal case to feed dynamic options to select.
Or is it possible to work around this without side effects?
thanks again for your work.

**Comment by larrybotha** [comment]
@damooo does https://github.com/tjinauyeung/svelte-forms-lib/pull/24 help with dynamically loaded options?

e.g.

1. render form, select's default value is `null` / `undefined`
2. request data
3. on response, set select's default value using `updateInitialValues`

**Comment by damooo** [comment]
Yup, that's pretty good api. thanks for that.
