### ISSUE TITLE
Add missing env vars to Travis

### ISSUE THREAD

**Issue by larrybotha** [tjinauyeung/svelte-forms-lib#42]
@tjinauyeung the build on Travis is failing: https://travis-ci.com/github/tjinauyeung/svelte-forms-lib/jobs/362498395

You'll need to add a Github token to Travis to allow Travis to push updates here:

<img width="875" alt="Screenshot 2020-07-19 at 08 27 59" src="https://user-images.githubusercontent.com/1510520/87875895-f96beb00-c999-11ea-9099-8b97b61ce6b0.png">

> A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.
Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository tjinauyeung/svelte-forms-lib.

**Comment by tjinauyeung** [comment]
Fixed it! 

<img width="1555" alt="Screenshot 2020-07-20 at 08 35 02" src="https://user-images.githubusercontent.com/10131999/87906986-fb01e580-ca63-11ea-9497-fdf8af93ff02.png">
