### ISSUE TITLE
Nope validator

### ISSUE THREAD

**Issue by meigo** [tjinauyeung/svelte-forms-lib#44]
Would it be thinkable to implement [Nope](https://github.com/bvego/nope-validator) validation as it's similar to Yup but claims to be considerably smaller and faster?

**Comment by larrybotha** [comment]
It'd be good to not have `yup` as a hard dependency, but instead as a fallback when using schema validation.

By doing this we could allow a user to supply a provider for schema validation, otherwise use an internal provider (the current yup implementation, but passed in as a parameter to `createForm`).

e.g. use `yup` by default:

```javascript
const {form, ...rest} = createForm({
	validationSchema: myFormSchema
})
```

vs providing a custom validation provider:

```javascript
const {form, ...rest} = createForm({
	validationSchema: myFormSchema,
	validationSchemaProvider: myNopeValidationProvider,
})
```

This could be implemented without a major version change, while allowing anyone to use any validation schema, as long as they provide a function to manage that validation.

**Comment by tiaanduplessis** [comment]
@meigo looks very nice. Might use it for a new project coming up. It should be possible use Nope with the validate config option:

```
<script>
  import { createForm } from "svelte-forms-lib";
  import Nope from "nope-validator";

  const schema = Nope.object().shape({
    email: Nope.string()
      .email()
      .required()
  });

  const { form, handleChange, handleSubmit, errors } = createForm({
    initialValues: {
      email: ""
    },
    validate: values => schema.validate(values),
    onSubmit: values => {
      alert(JSON.stringify(values));
    }
  });
</script>

  <form on:submit|preventDefault={handleSubmit}>

    <label for="email">email</label>
    <input
      id="email"
      name="email"
      on:change={handleChange}
      on:blur={handleChange}
      bind:value={$form.email}
    />

    <span>{$errors.email}</span>

    <button type="submit">Submit</button>
  </form>

```

Sandbox example: https://codesandbox.io/s/brave-meadow-u1g44?file=/App.svelte:0-766

**Comment by meigo** [comment]
Thanks @larrybotha & @tiaanduplessis. It actually looks very good, shaved off a big chunk from the bundle.
There is a problem though when validation succeeds, it's also present in sandbox example by tiaanduplessis and it's related related to this:
> Instead of throwing errors Nope simply returns the error object and if there are no errors it returns undefined.

Currently forms-lib seems to assume that there is existing error object represented all the time so additional error === undefined checks could be added where needed.

**Comment by tiaanduplessis** [comment]
@meigo I see. I agree that we should support the case of `validateFn` returning a Nullish value. Going to try out Nope on a project today to cut down on the bundle a bit :+1:
