### ISSUE TITLE
Why does isValid require all fields to be touched?

### ISSUE THREAD

**Issue by jdevine** [tjinauyeung/svelte-forms-lib#47]
I see that isValid from createForm is not called anywhere except a test, and the requirement that all fields need to be touched to return true doesn't make a lot of sense to me.

Should the function be removed?

**Comment by callmeberzerker** [comment]
Yeah, this is a bug 100%.

**Comment by tiaanduplessis** [comment]
@jdevine thank you for opening up the issue. I agree that this isn't the desired behavior and will address it over the weekend

**Comment by subpx** [comment]
Ive fixed this. Will raise a PR once a pending PR of mine is merged.
