### ISSUE TITLE
How to use CheckBoxs as an input option in a form.

### ISSUE THREAD

**Issue by GravyPouch** [tjinauyeung/svelte-forms-lib#49]
I'm sorry if I am missing something obvious but I am really stumped on how to create a checkbox, and I cant find anything in the documentation. I want to have the option for the user to select multiple options at a time. Just like this: https://www.w3schools.com/tags/att_input_type_checkbox.asp

, Any help would be appreciated. Thank you. 

I am creating input fields using this method:
`<label for="title">title</label>
      <select
        id="title"
        type="checkbox"
        name="title"
        on:change={handleChange}
        bind:value={$form.title}>
        <option />
        <option>Mr.</option>
        <option>Mrs.</option>
        <option>Mx.</option>
      </select>
      {#if $errors.title}
        <small>{$errors.title}</small>
      {/if}`

**Comment by larrybotha** [comment]
@GravyPouch something like the following?

https://codesandbox.io/s/svelte-forms-lib-49-dlwx6

**Comment by GravyPouch** [comment]
Thank you so much this is exactly what I was looking for.
