### ISSUE TITLE
Get values when using multiple submit buttons

### ISSUE THREAD

**Issue by hubert-ix** [tjinauyeung/svelte-forms-lib#50]
Is there a way to get the value of which submit button was pressed when we have several ones?
From what I've tried it looks like there isn't, but I thought I would ask just in case.

**Comment by larrybotha** [comment]
@hubert-ix you can use a proxy for the `handleSubmit` and intercept the event to determine which button was clicked, inspecting the `submitter` property:

```svelte
<script>
	const {handleSubmit} = createForm({...options});

	function handleSubmitProxy(event) {
		const {submitter: submitButton} = event;

		// do something with submitButton

		handleSubmit(event)
	}
</script>

<form on:submit|preventDefault={handleSubmitProxy}>
	// ...

	<button id="test-1">submit 1</button>
	<button id="test-2">submit 2</button>
</form>
```

<img width="373" alt="Screenshot 2020-09-10 at 17 44 51" src="https://user-images.githubusercontent.com/1510520/92818802-bae92000-f38d-11ea-9778-f89074d8efab.png">
