### ISSUE TITLE
how to set a variable such as validationError?

### ISSUE THREAD

**Issue by evdama** [tjinauyeung/svelte-forms-lib#51]
This is actually more of a question:

I have a button where I'd like to set `disabled` to true or false depending on wheter or not the user has checked a checkbox:
```html
<button disabled={ !checkedTermsOfService } type="submit">Start chatting</button>
```
Toggling `checkedTermsOfService` is done like this
```html
<input bind:checked={ checkedTermsOfService } id="termsofservice" type="checkbox" name="terms" value="accept">
```

**Question:**
I'd also like to disable the button when the another input field where the user supplies his `name` isn't valid
```html
<Field name="name" id="userName" type="text"/>
```

I'm using `Field` and `Form` and my `formProps` looks like this
```js
  const formProps = {
    initialValues:  { name: 'e.g. John Doe' },
    validationSchema: yup.object().shape({
      name: yup
        .string()
        .trim()
        .required('You left the name field empty... Please provide your temporary displayname! 😃')
        .min(3, 'Your name may not be less than 3 characters long! 🤓')
        .max(30, 'Your name may not be more than 30 characters long! 🤓')
    }),
    onSubmit: values => { handleSignUpUser(values) }
  }
```

My button from above would now look like this (having `validationError` in addition to `checkedTermsOfService`):
```html
<button disabled={ !checkedTermsOfService || validationError } type="submit">Start chatting</button>
```

Now how do I set/toggle `validationError` as I don't seem to have `$errors` available when I use the helper components such as `Field` and `Form` i.e. I don't use ` const { form, errors, state, handleChange, handleSubmit } = createForm({ ...})` which means I don't have the `$errors` observable and I can't use `$errors.name` in my html and or set `validationError` in my svelte `<script>` section?

Maybe there's a much simpler solution and I'm thinking to complicated based on my lack of internal knowledge of svelte-forms-lib...

**Comment by larrybotha** [comment]
As of https://github.com/tjinauyeung/svelte-forms-lib/pull/102 one can call `createForm` outside of form, and pass that value to `<Form />`. Outside of `<Form />` you'll then have access to `$errors`:

See https://github.com/tjinauyeung/svelte-forms-lib/issues/56#issuecomment-787099696 for an example.

Let me know if you have any questions!
