### ISSUE TITLE
Make validate function optional; Cannot read property 'then' of undefined at updateValidateField 

### ISSUE THREAD

**Issue by TylerRick** [tjinauyeung/svelte-forms-lib#52]
**Describe the bug**

Even with the basic example at https://svelte-forms-lib-sapper-docs.now.sh/basic, I'm getting this error:

![image](https://user-images.githubusercontent.com/14151/92283287-71439580-eeb4-11ea-8dda-76a628915c9a.png)

```
  function updateValidateField(field, value) {
    return validateFieldValue(field, value).then(function () {
      updateField(field, value);
    });
  }
```

**To Reproduce**

Use the example from https://svelte-forms-lib-sapper-docs.now.sh/basic

**Expected behavior**

No errors

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome, Firefox

**Comment by TylerRick** [comment]
Possibly the example just needs to be updated/fixed...

**Comment by TylerRick** [comment]
Looks like `createForm` _requires_ a `validate` function to be passed in.

Adding:
```
    validate: values => true
```

makes the error go away...

**Comment by TylerRick** [comment]
Well, I can't reproduce in [CodeSandbox](https://codesandbox.io/s/react-forms-lib-bug-report-esdl2?file=/App.svelte), so it must have been a problem on my end. Closing for now.

**Comment by TylerRick** [comment]
I take that back. I _did_ just run into it using the  [CodeSandbox template](https://codesandbox.io/s/react-forms-lib-bug-report-esdl2?file=/App.svelte), so it's not just a problem with my code. But it's only intermittent. When I reload that sandbox, it doesn't give any error when I submit now.

But I did just run into it in a different [Sandbox](https://codesandbox.io/s/eloquent-flower-zsjc8?file=/App.svelte) that's just as simple or simpler:

![image](https://user-images.githubusercontent.com/14151/92809996-fa097800-f371-11ea-9cd2-b27030068f39.png)

Why does it do this?

**Comment by larrybotha** [comment]
@TylerRick you're spreading `formProps` onto your `<form >`, but `formProps` doesn't return `onSubmit` - it returns _`handleSubmit`_, and that should be supplied to the form via the `on:submit` DOM event handler:

```svelte
<script>
  const {handleSubmit} = createForm({
    onSubmit: (values) => // do something with values,
  });
</script>

<form on:submit|preventDefault={handleSubmit}>
...
```

**Comment by TylerRick** [comment]
Yeah, I've seen the error intermittently with both `Form` component and using `createForm` — using examples straight from the docs. Strange.

**Comment by TylerRick** [comment]
Not super urgent since I'm not running into it anymore in my actual app, but just something to keep an eye out for...

**Comment by larrybotha** [comment]
This is happening because the return type of `validateFieldValue` is `Promise | undefined`, and `updateValidateField` assumes the return type is `Promise`: Here's the issue:

```javascript
  function validateFieldValue(field, value) {
    updateTouched(field, true);
    if (validationSchema) {
      isValidating.set(true);
      return util.reach(validationSchema, field).validate(value).then(() => util.update(errors, field, "")).catch(error => util.update(errors, field, error.message)).finally(() => {
        isValidating.set(false);
      });
    }

    if (validateFn) {
      isValidating.set(true);
      return Promise.resolve().then(() => validateFn({
        [field]: value
      })).then(errs => util.update(errors, field, ! util.isNullish(errs) ? errs[field] : "")).finally(() => {
        isValidating.set(false);
      });
    }

	// => not handling !validationSchema && !validateFn
  }
```

**Comment by larrybotha** [comment]
Thanks for reporting, @TylerRick, PR here at #55. Will get this merged once we have a review.
