### ISSUE TITLE
<Form> does not seem to be passing slot props to parent

### ISSUE THREAD

**Issue by TylerRick** [tjinauyeung/svelte-forms-lib#56]
**Describe the bug**
Looking at https://github.com/tjinauyeung/svelte-forms-lib/blob/master/lib/components/Form.svelte, it appears that it's trying to / supposed to be passing the form state into the slot.

Yet when I actually try to use those slot props, they seem to be stuck at some default value, `{}`.

Does someone have an example demonstrating how you can actually use these slot props? Perhaps https://svelte-forms-lib-sapper-docs.now.sh/helpers could be updated to document/demo this feature?

**To Reproduce**

https://codesandbox.io/s/frosty-monad-heihv?file=/App.svelte demonstrates both the non-working slot props in `Form` and a simple demo showing slot props working in `FakeForm`.

The context itself is getting updated (as proven by the `<ErrorMessage name="name" />` which consumes that context), but somehow the slot props are not getting updated.

**What could the problem be?**

Is this because context (unlike stores) are not reactive (see note at https://svelte.dev/docs#setContext)?

Hmm, but it [looks like](https://github.com/tjinauyeung/svelte-forms-lib/blob/master/lib/components/Form.svelte) actually passes the `form`, `errors`, `state`, etc. _stores_ into the slot. But if that's the case, how can you even use them? If I change `errors` to `$errors`, for example, I get this error:
```
Stores must be declared at the top level of the component (this may change in a future version of Svelte)
```

**Expected behavior**

I expect `errors` to be the same as `$errors` when using `createForm`, `state` the same as `$state`, and so on.

**Comment by TylerRick** [comment]
Maybe we just need to subscribe to them in `Form` and pass `$errors` instead of `errors` to `<slot>`?

**Comment by larrybotha** [comment]
hmmm, it seems that only child components of a component with a store exported via slot props can read the store:

```svelte
// App.svelte
<Form let:errors>
  <MyComp {errors} />
</Form>

// MyComp.svelte
<script>
	export let errors
</script>

<pre>{JSON.stringify($errors)}</pre>
```

Is there some other way to expose stores without the need for an additional component?

**Comment by larrybotha** [comment]
Defining the `Form` context outside of the form will address the store issue here - see #101 for proposal and #93 for an example

**Comment by larrybotha** [comment]
This can now be worked around since https://github.com/tjinauyeung/svelte-forms-lib/pull/102. To access the stores from where `<Form />` is rendered, pass the result of `createForm` in as `context`:

```svelte
<script>
	import {createForm, Form} from 'svelte-forms-lib'

	const formContext = createForm({
		// ...
	});
	const {errors} = formContext;
</script>

<Form context={formContext}>
	<!-- ... -->
	<pre>
		{JSON.stringify($errors)}
	</pre>
</Form>
```

Svelte doesn't appear to allow one to bind to a store exposed via a slot prop.

**Comment by letmejustputthishere** [comment]
> This can now be worked around since #102. To access the stores from where `<Form />` is rendered, pass the result of `createForm` in as `context`:
> 
> ```svelte
> <script>
> 	import {createForm, Form} from 'svelte-forms-lib'
> 
> 	const formContext = createForm({
> 		// ...
> 	});
> 	const {errors} = formContext;
> </script>
> 
> <Form context={formContext}>
> 	
> 	<pre>
> 		{JSON.stringify($errors)}
> 	</pre>
> </Form>
> ```
> 
> Svelte doesn't appear to allow one to bind to a store exposed via a slot prop.

can this be added to the helper component docs? took me a while to find this issue and the related answer :)
