### ISSUE TITLE
Value calculation

### ISSUE THREAD

**Issue by codechips** [tjinauyeung/svelte-forms-lib#6]
Hi and thanks for a great library! IMO this is definitely the best one atm :muscle:

**Is your feature request related to a problem? Please describe.**

I would like to calculate a field value that depends on another field. Say that I have blog title in one input field and in the other field I would like to generate a slug based on the title field. I also want to do this only if the slug field has not yet been touched. The reason for that is that if title field always acts as "master" a user will not be able to choose a custom slug. Hope that makes sense.

**Describe the solution you'd like**

Be able to pass some kind of custom input handler but I am not sure what arguments it should have because it would need access to some internal stuff deep down.

Maybe there is another, better approach that would let us use Svelte's reactivity, meaning that you setup a handler in your svelte file where you bootstrap your form, listen for changes to the $form and $touched stores somehow and act there. 

As I say, I am not sure on how to solve this.

**Additional context**

Maybe also be able to pass a custom onInput handler to helper components directly?

**Comment by larrybotha** [comment]
@codechips not sure if this even applicable to you anymore, but a recent release exports `updateField`: https://github.com/tjinauyeung/svelte-forms-lib/blob/master/lib/createForm.js#L162

You could use a reactive statement to update your field's value based on other values:

```svelte
$: (!$touched.slug) {
  const slug = $form.title.replace(/\s/g, '-')

  updateField('slug', slug);
}
```

Let me know if this doesn't help and I'll reopen.
