### ISSUE TITLE
Variable initialized by array becomes "modified"

### ISSUE THREAD

**Issue by Bighamster** [tjinauyeung/svelte-forms-lib#65]
**Describe the bug**

Variable initialized by array becomes "modified"

**To Reproduce**

[Example on codesandbox](https://codesandbox.io/s/epic-snow-ddurq?file=/App.svelte)

**Expected behavior**

Variable initialized by array should not be "modified"

**Comment by rccc** [comment]
Hello,

Any chance someone give an answer ? 

@tjinauyeung ?

**Comment by larrybotha** [comment]
@rccc I've started work on the following branch to address this: https://github.com/tjinauyeung/svelte-forms-lib/compare/fix-invalid-modified-state-on-initialization
