### ISSUE TITLE
Ability to customize yup validation messages

### ISSUE THREAD

**Issue by mhatvan** [tjinauyeung/svelte-forms-lib#70]
**Is your feature request related to a problem? Please describe.**
When I use the library with yup validations, the error messages read like this: `comment is a required field`.
It would be great to be able to use the yup validation errors and customize them in a way that they are more meaningful to the user.

**Describe the solution you'd like**
It would be great to receive the error message that would be displayed through a callback and improve them to be more understandable.

Examples include: "Name must be at least 5 characters long", "Password needs to include a special character", etc.

**Describe alternatives you've considered**
I know that `svelte-forms-lib` also offers custom validations, but the yup variant is more concise and handles different cases automatically without the need for e.g. a regex.

**Comment by larrybotha** [comment]
@mhatvan you can provide custom error messages to yup, either as a string, or via a callback:

```javascript
const validationSchema = object({
  head: string()
	.required("Wheeeeez yaaaaaaaaw heeeeead aaaat at?")
	.min(5, value => `${value.length} is just not enough!`),
});
```

Is this what you're looking for?

**Comment by mhatvan** [comment]
Oh, this looks perfect! I checked their documentation but didn't see this. Thank you ;)
