### ISSUE TITLE
Form array is no longer working

### ISSUE THREAD

**Issue by silentworks** [tjinauyeung/svelte-forms-lib#79]
**Describe the bug**

Whenever you try to create a form array the error nodes aren't being created. I suspect this commit https://github.com/tjinauyeung/svelte-forms-lib/commit/704f461f894de6893309e59b98d706fe935256b8 caused this issue to happen. When I roll back to version 1.2.2 of the library it is all working as expected.

**To Reproduce**

You can see the errors here
https://codesandbox.io/s/recursing-mccarthy-wne6b?file=/App.svelte

**Expected behavior**

This should not error and the $errors store should have some default array values but instead, it has an empty string as its value.

**Comment by larrybotha** [comment]
@silentworks thanks for reporting! Awaiting approval of a PR over at #80 to address this.

**Comment by larrybotha** [comment]
@silentworks this should be fixed as per #80. You can pull 1.3.1 for the updates.

**Comment by silentworks** [comment]
@larrybotha thanks for this, it works like a charm.

**Comment by leocaseiro** [comment]
mm, seems that this PR introduce an error for primitive arrays: https://github.com/tjinauyeung/svelte-forms-lib/issues/185
