### ISSUE TITLE
<ErrorMessage/> for <Field type='checkbox'/> behaving odd

### ISSUE THREAD

**Issue by evdama** [tjinauyeung/svelte-forms-lib#8]
I've this html markup

```html
                <Field name="terms" type="checkbox"/>
                <span>I agree to Foos <a href='termsofservice'>terms of service.</a></span>
                <ErrorMessage name="terms"/>
```

with this Yup validation object

```js
  const formProps = {
    initialValues:  {  terms: false  },
    validationSchema: yup.object().shape({
      terms: yup.boolean().oneOf([true], 'You must agree to our terms of service!')
    }),
    onSubmit: values => {...}}
```

When I focus and then blur the checkbox without checking it it thows the error. That's expected. However, even if I check it after focus, then blur (i.e. leave it using TAB or the mouse), the error message doesn't disappear.

Before user interaction, all ok

![image](https://user-images.githubusercontent.com/39374084/74502446-d0789300-4eed-11ea-9f3b-810e48838e6f.png)

After focus and blur, as expected, the Error message appears
![image](https://user-images.githubusercontent.com/39374084/74502508-10d81100-4eee-11ea-882e-59217264680a.png)

However, even after checking the checkbox, the error message sticks around?!
![image](https://user-images.githubusercontent.com/39374084/74502563-29e0c200-4eee-11ea-9496-05aaff0bb0e8.png)

**Comment by tjinauyeung** [comment]
Made a PR to fix this issue — https://github.com/tjinauyeung/svelte-forms-lib/pull/17. Released in another minor version.
