### ISSUE TITLE
Typescript defs?

### ISSUE THREAD

**Issue by howesteve** [tjinauyeung/svelte-forms-lib#81]
Hello all,

Are there typescript defs for this project? I'd really like to use it...

Thanks

**Comment by larrybotha** [comment]
Hey @howesteve 

No TypeScript definitions yet, but if you have time a PR would be appreciated!

**Comment by howesteve** [comment]
How about porting the whole project to typescript? Looks easier to me. Is that an option?

**Comment by larrybotha** [comment]
Ye, that'd be a better alternative. It's actually a task outlined in https://github.com/tjinauyeung/svelte-forms-lib/issues/34 which is free for anyone to pick up.
