### ISSUE TITLE
Change setContext and getContext to use an actually string instead of an empty object

### ISSUE THREAD

**Issue by silentworks** [tjinauyeung/svelte-forms-lib#85]
**Is your feature request related to a problem? Please describe.**
When trying to extend the library and create your own components, there is no way to get the original form properties that were created in the Form component. 

**Describe the solution you'd like**
Changing the setContext key to be a string like "svelte-forms-lib" instead of an empty object would make this possible, this would mean that every child component of Form could get access to all information in its context.

**Comment by larrybotha** [comment]
@silentworks an alternative may be to export the key for you to use within your components. Would that be useful?
