### ISSUE TITLE
Dynamic Yup schema validation from JSON

### ISSUE THREAD

**Issue by caschbre** [tjinauyeung/svelte-forms-lib#9]
**Is your feature request related to a problem? Please describe.**
Some forms may be dynamically created from configuration in a database, json file, etc. Given the syntax of yup, it takes some work to turn configuration into yup validation. It would be fantastic if a schema (e.g. json) could be used to dynamically generate the yup validation.

**Describe the solution you'd like**
From what I've found so far, a solution along the lines of this might work well as part of this module.
https://stackoverflow.com/questions/56725383/create-dynamic-yup-validation-schema-from-json

**Describe alternatives you've considered**
Right now I'm looking to implement the stackoverflow link separately but thought it would be a good fit as part of this module.
Edit: Just found the following: https://github.com/kristianmandrup/schema-to-yup
Edit: Found this one noted on the yup github page: https://github.com/WASD-Team/yup-ast

**Comment by larrybotha** [comment]
The suggestions in the edits look like good solutions to this. Adding a feature like this to `svelte-forms-lib` would add bloat, and tie `svelte-forms-lib` even more strongly to `yup`. Ideally `svelte-forms-lib` would be validation library agnostic.

I'll close this out, as it seems reasonable for it to leave it up to the user to generate a schema from JSON to keep `svelte-forms-lib` lean and less coupled.
