### ISSUE TITLE
Refactor utilities / consider alternative packages

### ISSUE THREAD

**Issue by pixelmund** [tjinauyeung/svelte-forms-lib#91]
**Is your feature request related to a problem? Please describe.**
Currently we are dependent on lodash.isequal which is in my opinion quite a huge module to include.
I also found out that the reach function in utils.js is never used anywhere, the reach function(getIn) uses forEach from property-expr, i don't really know why we need it.

**Describe the solution you'd like**
Consider much faster and smaller alternatives like [dequal](https://github.com/lukeed/dequal) only a few hundred bytes.
I already tested it with dequal and all the tests pass.
If the reach function is not important i would suggest removing the function and property-expr to reduce the bundle size even more.

**Describe alternatives you've considered**

**Additional context**

**Comment by larrybotha** [comment]
@pixelmund excellent - when adding lodash.isequal I was looking for something to quickly fix a bug, so I was quite sure it was a dirty fix. I didn't know about `dequal` - I'll happily accept a PR for the update.

Good find on those unneeded exports.

I've dealt with replacing `lodash.iseqaul` and removing unnecessary utils in #92
