### ISSUE TITLE
Return array of all validation errors

### ISSUE THREAD

**Issue by MarbTrek** [tjinauyeung/svelte-forms-lib#94]
**Is your feature request related to a problem? Please describe.**
`$error["field"]` returns 1 validation error at a time.

**Describe the solution you'd like**
Would like a list of all validation errors.

**Describe alternatives you've considered**
Passing an array of all error messages matching the field in question works.

```javascript
function  validateFieldValue(field){
//Workaround
.catch((yupErrors) => {
          if (yupErrors && yupErrors.inner) {
            const vals = []
            yupErrors.inner.forEach(v => {
              v.path === field && vals.push(v.message)
            })
            return util.update(errors, field, vals)
          }
          return util.update(errors, field, error.message)})
}
```

**Additional context**
Not thoroughly tested for side-effects.

**Comment by larrybotha** [comment]
@MarbTrek do you have a minimal example schema that you'd expect an array of errors from?

**Comment by MarbTrek** [comment]
```
yup
  .string()
  .min(8, "Password must contain at least 8 characters.")
  .matches(/[^a-zA-Z0-9\-\/]/, "Password must be alphanumeric")
```
Say you have the above validation schema. For my purposes, it'd help users to know each outstanding error remaining. That way they can fix them all at once versus piecemeal.

If this feature is desired, it may be helpful to add an ``$errorsList`` store to avoid any conflicts with & utility of how the current ``$errors`` store functions.

**Comment by larrybotha** [comment]
@MarbTrek what validation function are you calling to get all the validations at once with `yup`?

With `validate` and `validateSync` it seems like only a single error is thrown:

```js
const s = yup.string().min(2, 'min failed').matches(/0/, 'match failed');

// 1
s.validateSync('00') // => validates

// 2
s.validateSync('0')
/*
ValidationError: min failed
{
  value: '0',
  path: '',
  type: 'min',
  errors: [ 'min failed' ],
  inner: [],
  params: {
    value: '0',
    originalValue: '0',
    label: undefined,
    path: '',
    min: 2
  }
}
*/

// 3
s.validateSync('x')
/*
ValidationError: min failed
{
  value: 'x',
  path: '',
  type: 'min',
  errors: [ 'min failed' ],
  inner: [],
  params: {
    value: 'x',
    originalValue: 'x',
    label: undefined,
    path: '',
    min: 2
  }
}
*/
```

From what you're saying I'd expect _3_ to return an array of errors. Is there some mechanism in `yup` that allows one to walk through all potential validation errors on a single property?

**Comment by MarbTrek** [comment]
My fault, `create-form.js` uses the `validateAt` function. I neglected to include a change to line 68. From `.validateAt(field, get(form))` to `.validateAt(field, get(form), {abortEarly: false})`.

I believe the default behaviour is to abort early. I imagine that makes it more performant, so all the more reason to add this feature as a separate function for devs who only need one error at a time. Assuming this feature is wanted outside of just myself to begin with.

**Comment by larrybotha** [comment]
@MarbTrek ye, this sounds like a good candidate for writing a custom validation function and passing it to `createForm`s `validate` config:

```svelte
const {form} = createFor({
	validate({[someKey]: someValue}) {
		try {
			const validation = mySchema.validateAt(someKey, get(form), {abortEarly: false})
		catch(err) {
			// handle yup error
		}
	}
})
```

^untested

Does this help?

**Comment by MarbTrek** [comment]
Probably. I may have to pass a custom validation function anyway because I'd also like to push server-side errors into the array eventually. 

For now though, how do you pass `form` into `validateAt` before it's defined?

**Comment by larrybotha** [comment]
@MarbTrek that `form` defined inside `validateAt` should be a reference to the `form` scoped outside at the `createForm` call - `validateAt` is a closure, and closures have access to values in their parent scopes.

Let me know if you have any trouble! You can post a link to a CodeSandbox example using the following template if you run into issues: https://codesandbox.io/s/react-forms-lib-bug-report-esdl2?file=/App.svelte - I'll help where I can :)

**Comment by larrybotha** [comment]
Closing this issue as it seems appropriate to use a custom validation function.

Feel free to open if there are any questions or recommendations
